### ISSUE TITLE
Added to build.gradle still cannot find Horizon class

### ISSUE THREAD

**Issue by NehaDhanwani** [Yalantis/Horizon#11]
I added the library by adding compile 'com.yalantis:eqwaves:1.0' but cannot import Horizon and hence unable to use library

**Comment by Cool04ek** [comment]
Hi. Please, specify what error do you get? If no error, than what does your build.gradle file look like?

**Comment by Cool04ek** [comment]
@NehaDhanwani I have pushed fix and uploaded new lib to maven. Please, try **compile 'com.yalantis:eqwaves:1.0.1'** instead

**Comment by NehaDhanwani** [comment]
@Cool04ek : Thanks, able to add and use now. Is it possible to customize colors? Can I display it on light background?

**Comment by Cool04ek** [comment]
Background colour is one of the parameters you have to pass when create Horizon instance. As for the waves colour, for now they are hardcoded in the VerticesDataGenerator. You can change it by yourself. Later, we will provide update with customisation.

**Comment by NehaDhanwani** [comment]
Thanks! It works :)
