### ISSUE TITLE
Can Horizon work without own audio recorder?

### ISSUE THREAD

**Issue by XinwenCheng** [Yalantis/Horizon#23]
Hi,

I'm using 3rd-party audio service in my app, it has a capsuled audio recorder instance, so it conflicts with Horizon, how can I use Horizon for this situation?

Thanks!

**Comment by HitRoxxx** [comment]
Yes You can I am Using it . just pass byte[] from your recorder

**Comment by XinwenCheng** [comment]
@HitRoxxx I'm using Nuance Speech Recorder, I can't get byte[] from it, just can get volume value, it's in Integer type. And I read a little bit code of Horizon, seems it passes byte[] to native method, can't just set by volume values. Can I just ignore that native invocation?

**Comment by HitRoxxx** [comment]
audioRecord.read(new short[pullSizeInBytes], 0, pullSizeInBytes);
Your Recorder should use it in  reading data, u can make an interface and get that short [] or byte [] data from it and pass to horizon

**Comment by XinwenCheng** [comment]
Sorry, it's not my recorder, it's capsuled in third-party plugin which I use. Thanks for your suggestion, I'll try to find out other ways.
