### ISSUE TITLE
Rendering not working in Cyanogen 12.1

### ISSUE THREAD

**Issue by ppamorim** [Yalantis/Horizon#4]
Hi.
I have a LG G2 with Cyanogen 12.1 installed.. The render works by 0.5-1 second and freezes. On my another device, Motorola G2, works fine.
is it a problem with Cyanogen or with the library?

**Comment by Cool04ek** [comment]
Please check the latest update. If it doesn't fix your issue, please, provide more info about your freeze. Some log info would be appreciated.
