### ISSUE TITLE
Can't add library to project

### ISSUE THREAD

**Issue by marianpavel** [Yalantis/Horizon#6]
Hi, I am trying to add the library to the project ( compile 'com.yalantis:eqwaves:1.0.0' )
But android studio can't resolve it.

**Comment by marianpavel** [comment]
On website: 
compile 'com.yalantis:horizon:1.0.0’

on Github:

compile 'com.yalantis:eqwaves:1.0.0'

Tried both of them :(

**Comment by Cool04ek** [comment]
It should be like this: compile 'com.yalantis:eqwaves:1.0'
Looks like we have mistype in description

**Comment by courtofowls** [comment]
still facing it.. Not able to find class Horizon after I add compile 'com.yalantis:eqwaves:1.0' in build.gradle
